#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    BEGIN;
    CREATE USER $POSTGRES_SERVICE_USER WITH PASSWORD '$POSTGRES_SERVICE_PASSWORD';
    GRANT CONNECT ON DATABASE $POSTGRES_DB TO $POSTGRES_SERVICE_USER;
    GRANT USAGE ON SCHEMA public TO $POSTGRES_SERVICE_USER;
    GRANT SELECT, INSERT ON ALL TABLES IN SCHEMA public TO $POSTGRES_SERVICE_USER;
    GRANT SELECT, USAGE ON ALL SEQUENCES IN SCHEMA public TO $POSTGRES_SERVICE_USER;
    END;
EOSQL
